<%@ Page Title="Hakkımızda" Language="C#" MasterPageFile="~/rite.master" AutoEventWireup="true" CodeFile="Hakkımızda.aspx.cs" Inherits="Hakkımızda" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    İlk önce varsa gmail adresimizi ku llanıyoruz. Yoksa açıyoruz. -freenom&#39;a giriyoruz, sağ üstte SIGN IN var ona basıyoruz. -karşımıza çıkan tablonun aşağısında; &quot;SIGN IN&quot; ve &quot;CONTINUE WITH FACEBOOK&quot; var. SIGN IN; gmail oluyor. Ona basıyoruz ve gmail hesabımızı giriyoruz sonra kayıt bölümü bitiyor. -Üstte &quot;SERVICES&quot; var ona basıyoruz, sonra &quot;REGISTER A NEW DOMAIN&quot; e basıyoruz. -Orada istediğimiz site ismini yazıyoruz ve &quot;CHECH AVAILABILITY&quot; ye basıyoruz. -Karşımıza tk, ml, ga, cf ve gq çıkıyor. Onlardan birini seçiyoruz (&quot;GET IN NOW!&quot; a basıyoruz). -bir üstünde &quot;CHECKOUT&quot; var ona basıyoruz. -Sonra sağda &quot;3 MONTHS @ FREE&quot; var ona basıyoruz 12 ayı seçiyoruz ve &quot;CONTINUE&quot; a basıyoruz. -sonra aşağıda &quot;I HAVE&quot; ile başlayan cümleyi tikliyoruz ve &quot;COMPLETE ORDER&quot;a basıyoruz -Daha sonra 000webhost&#39;u açıyoruz. -Sağ üstte &quot;FREE SIGN UP&quot; a basıyoruz. -Sonra oraya gmail imizi, gmail şifremizi ve freenom da aldığımız sitenin adını (mesela; oznurgunyol.tk ) yazıyoruz. Ve ilerliyoruz. -az aşağıda 
&quot;MANAGE WEBSITE&quot; yazıyor ona basıyoruz karşımıza gmail doğrulamamız ile ilgili bir bilgicik geliyor ona &quot;OK&quot; yanıtını veriyoruz. -Aşağıda arkası krem rengi olan, ve sağında &quot;RESEND CONFIRMATION&quot; yazan kısıma basıyoruz ve bizim gmailimize bir doğrulama gönderiyor. Onu doğruluyoruz gmailden (geç gelebilir). NOT: bu arada karışıklık yaşamamak için gmail ile webhost un şifresini aynı yapını! -doğruladıktan sonra webhost sayfasını menüler gelsin diye yeniliyoruz. -gelen menüde &quot;SET WEB ADRESS&quot; var ona basıyoruz. Karşımıza çıkan gönderinin boş yerine basıyoruz. -az aşağıda &quot;OWN DOMAIN&quot; var &quot;USE DOMAIN&quot; var onun içinde ona basıyoruz ve sitemizin ismini yazıyoruz ve park domain e basıyoruz. -aşağıda da domain vs var sitemizin karşısında &quot;MANAGE&quot; var ona basıyoruz ve &quot;RECHECK NAMESERVERS&quot; a basıyoruz. -server ları gmaile gönderecek gene zaman alabilir. -gmaile mesaj geldikten sonra freenom&#39;a giriyoruz. -üstte; &quot;services&gt;my domains&quot;e basıyoruz. -&quot;MANAGE DOMAIN&quot;e basıyoruz. -&quot;MANAGEMENT 
TOOLS&gt;NAMESERVERS&quot;a basıyoruz. -2 radiobutton var alttakine basıyoruz. Sonra 6 tane nameservers var 2 tanesine gmaile webhost tan gönderdiğimiz serverları giriyoruz ve kaydediyoruz. -Sonra webhost a giriyoruz. Sağ üstte &quot;SETTINGS&quot; var ona basıyoruz ve içerisinde &quot;GENERAL&quot; var ona da basıyoruz. -sonra filezilla ya giriyoruz. -webhost ta host name falan var. Web hosttaki host name&#39;i, port&#39;u ve username&#39;i filezilla ya giriyoruz. -filezilla da ki password bölümü kalıyor işte burada yazdığım notun önemini anlıyoruz. İşte o gmail webhost un şifresini giriyoruz. Sonra &quot;QUICKCONNECT&quot; e basıyoruz karşımıza çıkan gönderiye &quot;OK&quot; diye yanıt veriyoruz. -Sonra sol altta yayınlayacağımız sitenin klasörünü seçiyoruz onun da altında klasörün içeriği çıkacak onların hepsini sağ altta bulunan &quot;PUBLİC&quot; e atıyoruz ve bitiyor. -SİTE YAYIMLAMA İŞİ BİTİYOR ZAMAN ALABİLİR SİTENŞN YAYIMLANMASI<p>
</p>
</asp:Content>

